phoenix-rtos/phoenix-rtos-ports

openssl/build.sh, sscep/build.sh
sscep was using openssl files from host (detected by pkgconfig).
Fixed by installing correct openssl .pc files in build directory.
DONE: DTR-9
=> sscep, openssl: openssl source fix

openssl/01-makefile-install_keeps_timestamps.patch, openssl/build.sh
With incremental build the installed openssl library and headers is
installed using "cp" which results in modified timestamp and rebuild of
all things needing openssl. This fix changes the install method to
"cp -a".
Fixes phoenix-rtos/phoenix-rtos-project#185
=> openssl: keep timestamps of installed headers and libs

dropbear/patch/0001-ps_dcsap_login.patch
`getpwnam` was using still `/etc/passwd`.
JIRA: DTR-213
=> dropbear: fix ps_login_service usage (custom getpwnam/getpwuid)

micropython/README.md, micropython/micropython-1.15-config/patches/06_os_main.patch
JIRA: PD-189
Removing `strlcat()` and `strlcpy()` related patches
After https://github.com/phoenix-rtos/libphoenix/commit/738e12e64ea64f7f4292c894fc6ac0fa6db1678b there is no need for supplementary definitions of `strlcat()` and `strlcpy()`.
=> micropython: remove strlcat and strlcpy patches

busybox/17-watchdog-read-file.patch
With this parameter watchdogd tries to open FILE and read no more
than 1K bytes from it. If file cannot be opened or data cannot be
read from it than watchdog counter doesn't not reset.
DONE: DTR-169
=> busybox: add "-r FILE" parameter to watchdogd

build.sh, mbedtls/README.md, mbedtls/build.sh, mbedtls/patches/01_disable_fuzz.patch, mbedtls/patches/02_rename_debug_var.patch, mbedtls/patches/03_avoid_relinking.patch, mbedtls/patches/04_set_devrandom_entropy.patch
- mbedtls: add mbedtls port: v2.28.0
Needed for azure iot sdk incoming port.
DONE: PD-272
https://github.com/phoenix-rtos/phoenix-rtos-doc/pull/119
=> mbedtls: add mbedtls port: v2.28.0

openssl/build.sh
- openssl: set openssldir to /etc/ssl
DONE: PD-300
The openssl directory was set to the install/ssl in _build before. The path to directory with certificates is based on openssldir value, so it should be set to some directory in phoenix root.
It's required for running azure-iot-sdk-c on ia32-generic-qemu
=> openssl: set openssldir to /etc/ssl

azure_sdk/build.sh, build.sh, busybox/build.sh, curl/build.sh, dropbear/build.sh, dropbear/patch/0003-autoconf_phoenix.patch, jansson/build.sh, libevent/build.sh, lighttpd/build.sh, lua/build.sh, lzo/build.sh, mbedtls/build.sh, micropython/build.sh, micropython/micropython-1.15-config/patches/04_mpy-cross_Makefile.patch, micropython/micropython-1.15-config/patches/07_os_Makefile.patch, openiked/build.sh, openssl/build.sh, openvpn/build.sh, pcre/build.sh, sscep/build.sh, wpa_supplicant/build.sh, zlib/build.sh
These changes bring us closer to being able to compile ports on macOS. Still, some ports do not compile (i.e Azure SDK on ia32-generic-qemu) but the changes will be made in subsequent pull requests.
=> Make it possible to compile part of the ports on macos

azure_sdk/build.sh, mbedtls/build.sh, openiked/build.sh
JIRA: CI-334
`TOPDIR` was obsoleted in favor of `PREFIX_PROJECT`
=> build: remove TOPDIR usage

busybox/build.sh
CI to pass: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/815
`clean` is being handled globally (whole build dir is being removed) 
JIRA: CI-334
=> busybox: remove dependency on CLEAN variable

micropython/micropython-1.15-config/patches/08_os_varia.patch
=> micropython: Fix patch 08 - there're no custom dirent types anymore

busybox/19-enable-testcase-logging.patch
=> busybox: enable testcase logging

lighttpd/patches/makefile_wstunnel.patch
WARN: only Makefile.in changed without Makefile.am to avoid necessary autogen run.
JIRA: DTR-460
=> lighttpd: Fix mod_wstunnel not being built in static build

busybox/20-fix-ash-nofork-interrupted.patch
Backported fix from Busybox v1.36.
If certain applets in `ash` are interrupted with `^C` it could cause a corruption of the system state, which causes all subsequent commands to cause segfaults. This has been fixed in later versions of Busybox and this PR backports the fix.
Closes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/890
=> busybox: fix ash segfaults after interrupting applet

azure_sdk/build.sh, coremark/build.sh, curl/build.sh, dropbear/build.sh, fs_mark/build.sh, lighttpd/build.sh, lua/build.sh, openiked/build.sh, openssl/build.sh, openvpn/build.sh, picocom/build.sh, sscep/build.sh, wpa_supplicant/build.sh
Some architectures, like armv7m, use a wrapper script for strip which expects specific arguments at the end. This change makes ports use strip in a specific manner so that they build properly on all architectures. The `-s` (`--strip-all`) flag is removed, as it probably is not appropriate for all architectures (which use their own symbol stripping flags) and seems to be the default action when no flag is passed.
Another approach is to modify phoenix-rtos-build/scripts/strip.py to behave just like the `strip` tool, but it is also quite problematical.
=> Update build scripts to be compatible with strip.py wrapper

busybox/09-ping-signal.patch, busybox/21-route-include-ip6_route.patch, busybox/22-ifconfig-ipv6.patch
* Added necessary nonblocking flag for socket used in ping6, following the existing solution for ping4
* Provided IPv6 addresses info for ifconfig
* Made `route.c` compile by including `net/ip6_route.h`
https://github.com/phoenix-rtos/phoenix-rtos-lwip/pull/93
https://github.com/phoenix-rtos/libphoenix/pull/355
=> busybox: add IPv6 support

build.sh
`DEBUG` is a common env variable in OSS programs to build unstripped/not-optimized/with-debug-info binaries - we almost never want to do it.
JIRA: CI-494
=> !build: forcefully disable DEBUG for ports

build.sh, coreMQTT/CMakeLists.txt, coreMQTT/build.sh
Porting a lightweight MQTT client library [coreMQTT](https://www.freertos.org/mqtt/index.html)
JIRA-NIL588
https://github.com/phoenix-rtos/phoenix-rtos-ports/pull/78
=> Add coreMQTT library

lua/patches/5.3.6/04-priority.patch
=> lua: add '-p prio' option

mbedtls/patches/02_rename_debug_var.patch, mbedtls/patches/04_set_devrandom_entropy.patch
JIRA: RTOS-1067
~~For host-generic platform, when `phoenix` is not defined, projects didn't build because `mbedtls_devrandom_poll()` was undeclared. I don't know if it's ok to allow using /dev/random for other OSs, so I moved `#if defined(phoenix)` clause over `MBEDTLS_ENTROPY_DEV_RANDOM`.~~
I ~~also~~ deleted some trailing/unneeded spaces.
~~Needed for compiling phoenix-rtos projects with mbedtls on host~~
=> mbedtls: remove extra whitespaces from patches

build.sh, smolrtsp/build.sh, smolrtsp/patches/01-installation.patch, smolrtsp/patches/02-ip_pmtudisc_want.patch
JIRA: PP-332
Add `smolrtsp` library port for streaming server
Adds a port for the `smolrtsp` library. 
This library is a required dependency for the streaming server application, which is located in a separate submodule.
The streaming server application requires the `smolrtsp` library to handle the RTSP protocol.
The change has been manually tested. 
The server submodule builds and links successfully against the `smolrtsp` library. 
The server application starts, its streaming component initializes without errors, and the video streams correctly.
=> webuav: port smolrtsp library

smolrtsp/patches/02-ip_pmtudisc_want.patch
JIRA: PP-332
Fix UDP functionality.
Remove unsupported feature from the library.
Phoenix-RTOS does not implement the IP_PMTUDISC_WANT socket option.
=> smolrtsp: fix udp functionality
