openssl/build.sh

This needs https://github.com/phoenix-rtos/phoenix-rtos-build/pull/47 to be merged.

openssl: Fix Configure script call

---

busybox/12-runsv-poll_timeout.patch

busybox: fix runsv (uninterruptible poll)

---

build.sh
sscep/build.sh
sscep/patches/01-getopt.patch
sscep/patches/02-timeval.patch
sscep/patches/03-warnings.patch

sscep: add sscep

---

build.sh
libevent/build.sh
libevent/patches/01-mmap.patch
libevent/patches/02-gettime.patch
libevent/patches/03-tv_sec.patch

libevent: add libevent

---

busybox/13-make4.3fix-change_bb_version.patch
busybox/14-make4.3fix-remove_kbuild_str.patch

Imported 2 upstream patches.
Fixes phoenix-rtos/phoenix-rtos-project#170

busybox: fix incremental build with make 4.3

---

busybox/15-watchdog-includes.patch

...at least for imx6ull platform :).
JIRA: DTR-122

busybox: make watchdog compilable

---

sscep/patches/04-mime.patch

sscep: add mime patch

---

wpa_supplicant/config

wpa_supplicant: disable some unused features

---

.github/workflows/ci.yml

JIRA: CI-87
Mails are sent to continuous integration team, when some fails occur in github-actions workflows (steps other than build in Build job).
There was no information for ci team about fails not caused by user in gh-actions ci workflows

ci: additional mail notification for ci team

---

pcre/build.sh

JIRA: RTOS-123
Change source server for `pcre` to http://ftp.exim.org
Used http://ftp.pcre.org server to get `pcre` is no longer available.

pcre: change source server

---

busybox/16-syslogd-large-buf.patch

JIRA: DTR-209
https://github.com/phoenix-rtos/libphoenix/pull/153
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/275

busybox: increase syslogd socket buffer size

---

busybox/16-syslogd-large-buf.patch

DONE: DTR-209
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/280

busybox: set syslogd socket buffer size using SO_RCVBUF option

---

libevent/patches/04-poll.patch

JIRA: DTR-6
Fix for killing openiked.

libevent: add poll fix (signal reception)

---

jansson/build.sh

- use `install -p` to preserve timestamps in headers
- use "echo" instead of "ranlib" to not overwrite static lib with every recompile (note: using ar -s while linking instead)
JIRA: DTR-231

jansson: fix incremental build

---

build.sh
zlib/build.sh
zlib/patches/01-cmake.patch

JIRA: DTR-219
Required in lighttpd mod_compress.

zlib: add zlib

---

lighttpd/build.sh
lighttpd/patches/mod_compress_fix.patch

lighttpd: mod_compress detects and serves precompressed files

---

zlib/build.sh

DONE: DTR-219
Old URL is no longer valid after new version release.

zlib: url fix

---

busybox/build.sh
curl/build.sh
dropbear/build.sh
jansson/build.sh
libevent/build.sh
lighttpd/build.sh
lua/build.sh
lzo/build.sh
micropython/build.sh
openssl/build.sh
openvpn/build.sh
pcre/build.sh
sscep/build.sh
wpa_supplicant/build.sh
zlib/build.sh

JIRA: ISC-129
Change variable name
Follow change in https://github.com/phoenix-rtos/phoenix-rtos-build/pull/107
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/107
https://github.com/phoenix-rtos/phoenix-rtos-ports/pull/39

build: Change TOPDIR to PREFIX_PROJECT

---

zlib/build.sh

zlib: Translate LDFLAGS to gcc format

---

libevent/build.sh

libevent: preserve timestamps when installing to speed up interactive build

---

dropbear/build.sh
dropbear/patch/0001-ps_dcsap_login.patch

* dropbear: autodetect zlib availability to enable compression
* dropbear: fix/silent some compilation warnings
* dropbear: download from mirror if main location is unavailable
Main location is unavailable, all `dropbear` builds fail now.

dropbear: build fixes and enhancements

---

curl/build.sh
dropbear/build.sh
jansson/build.sh
libevent/build.sh
lighttpd/build.sh
lua/build.sh
lzo/build.sh
mbedtls/build.sh
micropython/build.sh
openiked/build.sh
openssl/build.sh
openvpn/build.sh
pcre/build.sh
sscep/build.sh
wpa_supplicant/build.sh
zlib/build.sh

provide mirror URL for all packages

---

build.sh
picocom/build.sh
picocom/picocom.patch
picocom/term.patch

Adding building process for picocom port for Phoenix-RTOS
- add `build.sh` script for building process (heavily based upon `micropython/build.sh` to minimize workload on this port)
- utilize two small patchfiles for missing libraries and defines
Using release 3.1 from here: https://github.com/npat-efault/picocom/releases
Source code available at: https://github.com/npat-efault/picocom
Archive mirror link: https://files.phoesys.com/ports/picocom-3.1.tar.gz
**Patchfiles:**
There are two patchfiles for `picocom.c` and `term.c` files. Patching consist of:
- adding missing libraries into `picocom.c`
- adding missing libraries int `term.c`
- adding `CRTSCTS` flag to `term.c` file
CRTSCTS  flag is BSD specific. Based on [termios(3) manual](https://man7.org/linux/man-pages/man3/termios.3.html): …

picocom: add picocom port

---

busybox/build.sh

busybox: add downloading from mirror on error

---

busybox/build.sh

busybox: fix downloaded file check

---

busybox/16-syslogd-large-buf.patch

busybox: syslogd: add cmdline option for custom RCVBUF size

---

dropbear/build.sh
micropython/micropython-1.15-config/patches/05_os_configs.patch

- micropython: fix non-symmetric patch
Commenting-out ALLOC_EXEC and keeping FREE_EXEC might result in invalid memory
release procedure (`unmap` instead of `free`).
JIRA: CI-334
- dropbear: fix passing external CFLAGS
JIRA: CI-334

Build fixes

---

build.sh
coremark_pro/build.sh
coremark_pro/make/arm-phoenix.mak
coremark_pro/make/i386-pc-phoenix.mak
coremark_pro/make/phoenix-gcc.mak
coremark_pro/make/riscv64-phoenix.mak
coremark_pro/make/sparc-phoenix.mak
coremark_pro/patches/01-stack_size.patch

add CoreMark-PRO port

---

build.sh
heatshrink/build.sh

heatshrink: Add heatshrink compression algorithm

---

build.sh
heatshrink/build.sh

Added heatshrink compression and decompression library and application.
JIRA: NIL-927
(cherry picked from commit 594dc386061b86ca9122773f8e9af78242381857)

heatshrink: Add heatshrink compression library (backport to release/3.3)

---

build.sh

Backport to release/3.3
build.sh: update HOST and HOST_TARGET assignments
(cherry picked from commit addc54a157e50f9b770e1731bb3c34add7032e10)

build.sh: update HOST and HOST_TARGET assignments (backport to release/3.3)

---

lua/patches/5.3.6/05-add-healthcheck.patch

lua: correctly consume heartbeat even when called with coroutine state

---

lua/patches/5.3.6/05-add-healthcheck.patch
lua/patches/5.3.6/06-exclude-file-searchers.patch

Backports https://github.com/phoenix-rtos/phoenix-rtos-ports/pull/108 to release 3.3 branch

lua: add healthchecking and file searchers exclusion (backport to release/3.3)
